sudo: required
dist: trusty
services: docker
setup:
- docker pull blang/latex:ctanfull
script:
- "./build.sh"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FOK4ZwG+PXXJLgJ3O3v18/mUwRuX6oncz1q8/9jUN05uGSW2clC8DTzj9OL+x3tEtPOCTPj2fpYdmYMwbhVwzZ17hQKqX+SMZoyJlXfI1DBOID9GCGdr6UN6+N96qCFLQStz5ymFfUvlCMyeMXvCaK5AqCuk2IRJPKXb3WAY9iSV07sqrF1CDwL5/hNE8XFbUrFG5whItAuKrXlkywqVYiL7qTfmz5OJ/AjzvB5ybt0Bc/M2Kj7vTjq20FJ9x+IUsE4jn7hDyLEiEX3djvHuzwIxpdHRvPKiOn9NbuCuOnGaDCq9Q5o9OQCjhnNcwZ9khotd9dFGRmW766Ouf02ZQmkJLjQwJQkKIWGkOadWhzsvuByDQD/Fx0Kumky5MdGsfp+/6YYjiBAqUAKVSfsQSIxayrGcykIHf27DW1tS/hblnfjWqIIDFYYxMZH7sNmsp2EQv8PDF4fQG32Xin6JWiNT4nJLQK2nqlTxTmmaoGtXZmjYIZqHRKQLEeZ/WYwH+xxT93SHp4MrwrYLFvTABH/nEvxIN3cvOon4cLO78vde9Ce2vbU306T4KjpgbuC4ThfcaKoLTeoRiKcTLFyFul+DN6+Itno9Gd52VCpZeo+s8ZQPvrJXw2bijMI9KeCYj2/9+wT+YvcvBYeua/zYiVKpo63Fqfst4rPDGhRcvyc=
  file: build/centrifuge-protocol.pdf
  on:
    tags: true
